language: 
  node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

env:
  global:
    - export TEST_DATABASE_URL=postgresql://postgres@localhost:5432/edustripe_test_db
    - export REDIS_URL=redis://127.0.0.1:6379

services:
  - postgresql
  - redis

before_script:
  - psql -c 'create database edustripe_test_db; ' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - "yarn nyc"

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
